/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Dao.PlaylistSongDao;
import Dao.SongDAO;
import Model.PlaylistModel;
import Model.Song;
import service.PlaylistManager;
import java.awt.*;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.List;
import javax.swing.*;

/**
 * AddToPlaylist_Interface - UI for adding current song to a playlist
 * Displays playlists in a 3x3 grid using PlaylistCard components
 * Song continues playing in the background without interruption
 */
public class AddToPlaylist_Interface extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(AddToPlaylist_Interface.class.getName());

    private final Song currentSong;
    private final PlaylistSongDao playlistSongDao;
    private final SongDAO songDao;
    private JScrollPane playlistScrollPane;
    private JPanel playlistGridPanel;

    /**
     * Creates new form AddToPlaylist_Interface
     * 
     * @param song The song to add to playlist
     */
    public AddToPlaylist_Interface(Song song) {
        this.currentSong = song;
        this.playlistSongDao = new PlaylistSongDao();
        this.songDao = new SongDAO();

        initComponents();
        initPlaylistGrid();
        setupPlaylistGrid();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BackBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        SearchTextField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        Createnew = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NowPlaying = new javax.swing.JPanel();
        playlistCardRendererPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(89, 141, 193));
        jPanel1.setLayout(null);

        BackBtn.setBackground(new java.awt.Color(153, 153, 153));
        BackBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(255, 255, 255));
        BackBtn.setText("←Back");
        BackBtn.setBorder(null);
        BackBtn.addActionListener(this::BackBtnActionPerformed);
        jPanel1.add(BackBtn);
        BackBtn.setBounds(840, 590, 110, 40);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        SearchTextField.setBackground(new java.awt.Color(153, 153, 153));
        SearchTextField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SearchTextField.setText("Search");
        SearchTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchTextFieldFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchTextFieldFocusLost(evt);
            }
        });
        SearchTextField.addActionListener(this::SearchTextFieldActionPerformed);

        searchBtn.setBackground(new java.awt.Color(153, 153, 153));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/meteor-icons_search.png"))); // NOI18N

        Createnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/createNewPlaylistBtn_image.jpg"))); // NOI18N
        Createnew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Createnew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Createnew.setIconTextGap(0);
        Createnew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Createnew.addActionListener(this::CreatenewActionPerformed);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mellow logo.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Create New Playlist");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("Add To Playlist");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                .createSequentialGroup()
                                                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(57, 57, 57))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(153, 153, 153)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel2Layout.createSequentialGroup()
                                                        .addComponent(Createnew, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(153, 153, 153))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(123, 123, 123)))));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(SearchTextField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap(10, Short.MAX_VALUE)
                                                .addComponent(Createnew, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap()));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(-10, 0, 1080, 170);

        NowPlaying.setBackground(new java.awt.Color(89, 141, 193));
        NowPlaying.setForeground(new java.awt.Color(102, 102, 102));
        NowPlaying.setLayout(null);
        jPanel1.add(NowPlaying);
        NowPlaying.setBounds(20, 570, 520, 80);

        playlistCardRendererPanel.setBackground(new java.awt.Color(89, 141, 193));

        javax.swing.GroupLayout playlistCardRendererPanelLayout = new javax.swing.GroupLayout(
                playlistCardRendererPanel);
        playlistCardRendererPanel.setLayout(playlistCardRendererPanelLayout);
        playlistCardRendererPanelLayout.setHorizontalGroup(
                playlistCardRendererPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 970, Short.MAX_VALUE));
        playlistCardRendererPanelLayout.setVerticalGroup(
                playlistCardRendererPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 350, Short.MAX_VALUE));

        jPanel1.add(playlistCardRendererPanel);
        playlistCardRendererPanel.setBounds(10, 220, 970, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1025,
                                javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchTextFieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_SearchTextFieldFocusLost
        // TODO add your handling code here:
        if (SearchTextField.getText().equals("")) {
            SearchTextField.setText("Search");
        }
    }// GEN-LAST:event_SearchTextFieldFocusLost

    private void SearchTextFieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_SearchTextFieldFocusGained
        // TODO add your handling code here:
        if (SearchTextField.getText().equals("Search")) {
            SearchTextField.setText("");
        }
    }// GEN-LAST:event_SearchTextFieldFocusGained

    private void CreatenewActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CreatenewActionPerformed
        // Hide create new playlist functionality in add-to-playlist mode
        JOptionPane.showMessageDialog(
                this,
                "Please create new playlists from the Playlist menu",
                "Info",
                JOptionPane.INFORMATION_MESSAGE);
    }// GEN-LAST:event_CreatenewActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BackBtnActionPerformed
        // Just close this dialog - Player continues playing
        this.dispose();
    }// GEN-LAST:event_BackBtnActionPerformed

    private void SearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SearchTextFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_SearchTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        // Note: AddToPlaylist_Interface requires a Song parameter
        // It should be opened from Player.java, not run directly
        System.out.println("AddToPlaylist_Interface cannot be run directly. Open from Player.");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton Createnew;
    private javax.swing.JPanel NowPlaying;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel playlistCardRendererPanel;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables

    /**
     * Initialize playlist grid structure ONCE
     * Creates JScrollPane and playlistGridPanel that will be reused
     */
    private void initPlaylistGrid() {
        // Create grid panel with 3 columns and proper spacing
        playlistGridPanel = new JPanel(new GridLayout(0, 3, 20, 20));
        playlistGridPanel.setBackground(new java.awt.Color(204, 204, 204));
        playlistGridPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        // Create scroll pane ONCE
        playlistScrollPane = new JScrollPane(playlistGridPanel);
        playlistScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        playlistScrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        playlistScrollPane.setBorder(null);

        // Add scroll pane to parent container
        playlistCardRendererPanel.setLayout(new BorderLayout());
        playlistCardRendererPanel.add(playlistScrollPane, BorderLayout.CENTER);
    }

    /**
     * Setup playlist grid with PlaylistCard components in ADD mode
     */
    private void setupPlaylistGrid() {
        // Get playlists from cache (do NOT refetch)
        List<PlaylistModel> playlists = PlaylistManager.getInstance().getPlaylists();
        renderPlaylists(playlists);
    }

    /**
     * Render playlists in grid - ONLY clears and adds cards
     * Does NOT recreate panels or scroll panes
     */
    private void renderPlaylists(List<PlaylistModel> playlists) {
        // MUST clear old cards
        playlistGridPanel.removeAll();

        // Create PlaylistCard for each playlist in ADD mode
        for (PlaylistModel playlist : playlists) {
            PlaylistCard card = new PlaylistCard(
                    playlist,
                    PlaylistCard.Mode.ADD,
                    () -> handlePlaylistSelection(playlist));
            playlistGridPanel.add(card);
        }

        // REQUIRED: revalidate and repaint
        playlistGridPanel.revalidate();
        playlistGridPanel.repaint();

        logger.info("Rendered " + playlists.size() + " playlists in ADD mode");
    }

    /**
     * Handle playlist selection - show confirmation dialog and add song
     */
    private void handlePlaylistSelection(PlaylistModel playlist) {
        int result = JOptionPane.showConfirmDialog(
                this,
                "Do you want to add this song to \"" + playlist.getPlaylistName() + "\"?",
                "Add to Playlist",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (result == JOptionPane.YES_OPTION) {
            addSongToPlaylist(playlist);
        }
    }

    /**
     * Add song to playlist with FK integrity checks
     */
    private void addSongToPlaylist(PlaylistModel playlist) {
        try {
            // Step 1: Ensure song exists in database
            int songId = ensureSongInDatabase();
            if (songId <= 0) {
                JOptionPane.showMessageDialog(
                        this,
                        "Failed to register song in database",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Step 2: Insert into playlist_songs
            boolean success = playlistSongDao.addSongToPlaylist(
                    playlist.getPlaylistId(),
                    songId);

            if (success) {
                // Refresh cache
                PlaylistManager.getInstance().refreshCache();

                JOptionPane.showMessageDialog(
                        this,
                        "Song added to \"" + playlist.getPlaylistName() + "\" successfully!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);

                logger.info("Added song " + songId + " to playlist " + playlist.getPlaylistId());

                // Close this dialog and return to Player
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "Song is already in this playlist",
                        "Info",
                        JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            logger.severe("Error adding song to playlist: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                    this,
                    "Failed to add song: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Ensure song exists in database
     * For filesystem songs: check by file_path, insert if missing
     * For DB songs: use existing song_id
     */
    private int ensureSongInDatabase() {
        if (currentSong == null) {
            logger.warning("Current song is null");
            return -1;
        }

        // If song already has ID from DB, use it
        if (currentSong.getSongId() > 0) {
            logger.info("Song already has valid ID: " + currentSong.getSongId());
            return currentSong.getSongId();
        }

        // For filesystem songs, check by file_path
        if (currentSong.getFilePath() != null && !currentSong.getFilePath().isEmpty()) {
            logger.info("Checking if song exists by file_path");
            int existingId = songDao.getSongIdByFilePath(currentSong.getFilePath());
            if (existingId > 0) {
                logger.info("Found existing song: ID = " + existingId);
                return existingId;
            }

            // Insert new song
            logger.info("Inserting new song: " + currentSong.getTitle());
            int newId = songDao.insertSongIfNotExists(currentSong);
            if (newId > 0) {
                logger.info("Inserted song with ID: " + newId);
                return newId;
            }
        }

        logger.warning("Could not register song in database");
        return -1;
    }
}
