/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

//import java.awt.event.ActionListener;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import Dao.userDao;
import Model.UserData;
import Model.UserSession;

/**
 *
 * @author Asus
 */
public class AdminLoginUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(AdminLoginUI.class.getName());

    /**
     * Creates new form Login
     */
    public AdminLoginUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ForgotPassword = new javax.swing.JButton();
        loginAdminBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(955, 725));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 25)); // NOI18N
        jLabel1.setText("LOGIN ADMIN");
        jLabel1.setAlignmentX(5.0F);
        jLabel1.setAlignmentY(0.0F);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(580, 110, 220, 50);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 27)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("LOGIN ADMIN");
        jLabel7.setAlignmentX(2.0F);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(570, 90, 220, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mellow logo.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-20, 0, 290, 120);

        password.setBackground(new java.awt.Color(221, 220, 220));
        password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(153, 153, 153));
        password.setText("Enter your password");
        password.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(242, 242, 242),
                new java.awt.Color(235, 235, 235)));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addActionListener(this::passwordActionPerformed);
        getContentPane().add(password);
        password.setBounds(460, 300, 280, 30);

        email.setBackground(new java.awt.Color(221, 220, 220));
        email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(153, 153, 153));
        email.setText("Enter your email");
        email.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(236, 236, 236),
                new java.awt.Color(239, 238, 238)));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(460, 220, 280, 30);

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setText("Email :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(460, 190, 60, 20);

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setText("Password :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(460, 270, 70, 16);

        jLabel4.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel4.setText("A Personal Space just for you.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 540, 210, 30);

        ForgotPassword.setBackground(new java.awt.Color(242, 242, 242));
        ForgotPassword.setForeground(new java.awt.Color(51, 102, 255));
        ForgotPassword.setText("Forgot Password?");
        ForgotPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 236, 236), 1, true));
        ForgotPassword.addActionListener(this::ForgotPasswordActionPerformed);
        getContentPane().add(ForgotPassword);
        ForgotPassword.setBounds(610, 340, 130, 20);

        loginAdminBtn.setBackground(new java.awt.Color(153, 196, 239));
        loginAdminBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 16)); // NOI18N
        loginAdminBtn.setForeground(new java.awt.Color(89, 149, 209));
        loginAdminBtn.setText("LOGIN ADMIN");
        loginAdminBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 240, 241), 1, true));
        loginAdminBtn.addActionListener(this::loginAdminBtnActionPerformed);
        getContentPane().add(loginAdminBtn);
        loginAdminBtn.setBounds(610, 400, 150, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login and sign up bg111.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1000, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_passwordActionPerformed

    private void emailFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
        if (email.getText().equals("Enter your email")) {
            email.setText("");
        }
    }// GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
        if (email.getText().equals("")) {
            email.setText("Enter your email");
        }
    }// GEN-LAST:event_emailFocusLost

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
        if (String.valueOf(password.getPassword()).equals("Enter your password")) {
            password.setText("");
        }
    }// GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_passwordFocusLost
        // TODO add your handling code here:
        if (String.valueOf(password.getPassword()).equals("")) {
            password.setText("Enter your password");
        }
    }// GEN-LAST:event_passwordFocusLost

    private void ForgotPasswordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ForgotPasswordActionPerformed
        // TODO add your handling code here:
        AccountRecovery accountRecoveryView = new AccountRecovery();
        Controller.PasswordRecoveryController controller = new Controller.PasswordRecoveryController(
                accountRecoveryView);
        controller.open();
        this.dispose();
    }// GEN-LAST:event_ForgotPasswordActionPerformed

    private void loginAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loginAdminBtnActionPerformed
        attemptLogin();
    }// GEN-LAST:event_loginAdminBtnActionPerformed

    private void adminLoginActionPerformed(java.awt.event.ActionEvent evt) {
        attemptLogin();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /*
         * Create and display the form via controller to ensure listeners are attached
         */
        java.awt.EventQueue.invokeLater(() -> {
            // Ensure admin exists (default credentials)
            Dao.userDao udao = new Dao.userDao();
            udao.ensureAdminExists("admin", "admin@mellow.com", "admin123");

            AdminLoginUI loginView = new AdminLoginUI();
            loginView.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ForgotPassword;
    private javax.swing.JTextField email;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton loginAdminBtn;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables

    public void addAdminLoginListener(ActionListener listener) {
        loginAdminBtn.addActionListener(listener);
    }

    public javax.swing.JPasswordField getPasswordField() {
        return password;
    }

    public javax.swing.JTextField getEmailField() {
        return email;
    }

    private void attemptLogin() {
        String usernameOrEmail = email.getText().trim();
        String pwd = new String(password.getPassword());

        if (usernameOrEmail.isEmpty() || "Enter your email".equalsIgnoreCase(usernameOrEmail)) {
            JOptionPane.showMessageDialog(this, "Please enter your admin email or username.", "Validation Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (pwd.isBlank() || "Enter your password".equalsIgnoreCase(pwd)) {
            JOptionPane.showMessageDialog(this, "Password is required.", "Validation Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        userDao dao = new userDao();
        UserData admin = dao.authenticateAdmin(usernameOrEmail, pwd);

        if (admin != null) {
            UserSession.getInstance().setUserData(admin);
            JOptionPane.showMessageDialog(this, "Welcome, " + admin.getUsername(), "Login Successful",
                    JOptionPane.INFORMATION_MESSAGE);
            AdminDashboard admindashboard = new AdminDashboard();
            admindashboard.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Invalid admin credentials.", "Login Failed",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
}
