/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.SongController;
import Model.PlaySource;
import Model.Song;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import service.PlaybackManager;
import utils.NowPlayingState;
import utils.NowPlayingState.NowPlayingListener;

/**
 *
 * @author Asus
 */
public class AllSongs extends javax.swing.JFrame implements NowPlayingListener {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AllSongs.class.getName());
    private final SongController songController;
    private List<Song> allSongs;

    /**
     * Creates new form AllSongs
     */
    public AllSongs() {
        initComponents();
        songController = new SongController();
        
        // Fetch all songs from SongController and populate table
        loadAllSongs();
        setAllSongsColumnWidths();
        
        // Register as listener for now playing changes
        NowPlayingState.getInstance().addListener(this);
        
        // Add mouse listener for song selection
        // When user clicks a song: load full playlist into PlaybackManager and start playback
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = jTable2.rowAtPoint(evt.getPoint());
                if (row >= 0 && allSongs != null && row < allSongs.size()) {
                    Song selectedSong = allSongs.get(row);
                    
                    // Send full playlist and selected index to PlaybackManager
                    PlaybackManager.getInstance().setPlaylist(allSongs, row, PlaySource.ALL_SONGS);
                    
                    // Open Player UI with correct play source
                    Player playerWindow = Player.getInstance();
                    playerWindow.setPlaySource(PlaySource.ALL_SONGS);
                    playerWindow.setVisible(true);
                    
                    logger.info("Playing from AllSongs: " + selectedSong.getTitle());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SearchBar = new javax.swing.JTextField();
        Backtodashboard = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Playlist = new javax.swing.JButton();
        Likedsongs = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Likedsongs1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(994, 725));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mellowlogo.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 10, 210, 140);

        searchBtn.setBackground(new java.awt.Color(197, 191, 191));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/meteor-icons_search.png"))); // NOI18N
        searchBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(51, 51, 51)));
        getContentPane().add(searchBtn);
        searchBtn.setBounds(310, 50, 70, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("All Songs");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 120, 140, 32);

        SearchBar.setBackground(new java.awt.Color(160, 148, 148));
        SearchBar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        SearchBar.setForeground(new java.awt.Color(204, 204, 204));
        SearchBar.setText("               Search");
        SearchBar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        SearchBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchBarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchBarFocusLost(evt);
            }
        });
        SearchBar.addActionListener(this::SearchBarActionPerformed);
        getContentPane().add(SearchBar);
        SearchBar.setBounds(310, 50, 650, 30);

        Backtodashboard.setBackground(new java.awt.Color(40, 52, 46));
        Backtodashboard.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Backtodashboard.setForeground(new java.awt.Color(204, 204, 204));
        Backtodashboard.setText("Back to Dashboard");
        Backtodashboard.setBorder(null);
        Backtodashboard.addActionListener(this::BacktodashboardActionPerformed);
        getContentPane().add(Backtodashboard);
        Backtodashboard.setBounds(30, 620, 220, 40);

        jTable2.setBackground(new java.awt.Color(221, 219, 219));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "SN", "Title", "Artist", "Duration"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
        }

        jScrollPane2.setViewportView(jScrollPane3);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(340, 170, 610, 370);

        Playlist.setBackground(new java.awt.Color(40, 52, 46));
        Playlist.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Playlist.setForeground(new java.awt.Color(204, 204, 204));
        Playlist.setText("Playlists");
        Playlist.setBorder(null);
        Playlist.addActionListener(this::PlaylistActionPerformed);
        getContentPane().add(Playlist);
        Playlist.setBounds(110, 220, 130, 29);

        Likedsongs.setBackground(new java.awt.Color(40, 52, 46));
        Likedsongs.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Likedsongs.setForeground(new java.awt.Color(204, 204, 204));
        Likedsongs.setText("Liked Songs");
        Likedsongs.setBorder(null);
        Likedsongs.addActionListener(this::LikedsongsActionPerformed);
        getContentPane().add(Likedsongs);
        Likedsongs.setBounds(110, 280, 130, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconamoon_playlist.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 210, 41, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-park-outline_like.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 270, 50, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Untitled design (2).png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1000, 710);

        Likedsongs1.setBackground(new java.awt.Color(40, 52, 46));
        Likedsongs1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Likedsongs1.setForeground(new java.awt.Color(204, 204, 204));
        Likedsongs1.setText("Liked Songs");
        Likedsongs1.setBorder(null);
        Likedsongs1.addActionListener(this::Likedsongs1ActionPerformed);
        getContentPane().add(Likedsongs1);
        Likedsongs1.setBounds(110, 280, 130, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchBarFocusGained
        // TODO add your handling code here:
        if(SearchBar.getText().equals("               Search")){
            SearchBar.setText("");
        }
    }//GEN-LAST:event_SearchBarFocusGained

    private void SearchBarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchBarFocusLost
        // TODO add your handling code here:
        if(SearchBar.getText().equals("")){
            SearchBar.setText("               Search");
        }
    }//GEN-LAST:event_SearchBarFocusLost

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBarActionPerformed

    private void PlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaylistActionPerformed
        // TODO add your handling code here:
        Playlist Playlist = new Playlist();
        Playlist.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PlaylistActionPerformed

    private void LikedsongsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LikedsongsActionPerformed
        // TODO add your handling code here:
        likedsong likedsong = new likedsong();
        likedsong.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LikedsongsActionPerformed

    private void Likedsongs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Likedsongs1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Likedsongs1ActionPerformed

    private void BacktodashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BacktodashboardActionPerformed
        // TODO add your handling code here:
        UserDashboard UserDashboard = new UserDashboard();
        UserDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BacktodashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AllSongs().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backtodashboard;
    private javax.swing.JButton Likedsongs;
    private javax.swing.JButton Likedsongs1;
    private javax.swing.JButton Playlist;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables

    /**
     * Load all songs from SongController and populate the JTable.
     * Displays Title, Artist, and Duration.
     * Follows MVC principles - View fetches data from Controller.
     */
    private void loadAllSongs() {
        // Fetch all songs from controller
        allSongs = songController.getAllSongs();
        
        // Get table model and clear existing rows
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        
        if (allSongs == null || allSongs.isEmpty()) {
            return;
        }
        
        // Populate table with all songs (3 columns: Title, Artist, Duration)
        for (int i = 0; i < allSongs.size(); i++) {
            Song song = allSongs.get(i);
            String title = song.getTitle();
            String artist = song.getArtist();
            int durationSeconds = song.getDurationSeconds();
            String duration = String.format("%d:%02d", durationSeconds / 60, durationSeconds % 60);
            
            model.addRow(new Object[]{i + 1, title, artist, duration});
        }
    }

    private void setAllSongsColumnWidths() {
        javax.swing.table.TableColumnModel columns = jTable2.getColumnModel();
        columns.getColumn(0).setMinWidth(35);
        columns.getColumn(0).setPreferredWidth(45);
        columns.getColumn(0).setMaxWidth(55);
        columns.getColumn(1).setPreferredWidth(240);
        columns.getColumn(2).setPreferredWidth(180);
        columns.getColumn(3).setMinWidth(60);
        columns.getColumn(3).setPreferredWidth(70);
        columns.getColumn(3).setMaxWidth(80);
    }

    /**
     * Listen for now playing changes to update UI
     */
    @Override
    public void onNowPlayingChanged(Song song, boolean playing) {
        if (song == null) {
            logger.fine("Playback stopped");
            return;
        }
        
        logger.info("Now playing: " + song.getTitle() + " - " + song.getArtist());
        // UI updates can be added here if needed (e.g., highlight currently playing song)
    }
}
