/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author oakin
 */
public class ChangeUsername_Interface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChangeUsername_Interface.class.getName());

    /**
     * Creates new form ChangePassword_Interface
     */
    public ChangeUsername_Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        newUsernameTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(72, 118, 168));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        backBtn.setBackground(new java.awt.Color(159, 175, 192));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("←Back");
        backBtn.setBorder(null);
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        backBtn.addActionListener(this::backBtnActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Change Username");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(426, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 118);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setText("New Username:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(39, 207, 215, 44);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel4.setText("Password:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(39, 277, 238, 44);

        newUsernameTextField.setBackground(new java.awt.Color(204, 204, 204));
        newUsernameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newUsernameTextField.setForeground(new java.awt.Color(153, 153, 153));
        newUsernameTextField.setText("Enter Your Username");
        newUsernameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newUsernameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                newUsernameTextFieldFocusLost(evt);
            }
        });
        newUsernameTextField.addActionListener(this::newUsernameTextFieldActionPerformed);
        getContentPane().add(newUsernameTextField);
        newUsernameTextField.setBounds(290, 220, 379, 31);

        PasswordTextField.setBackground(new java.awt.Color(204, 204, 204));
        PasswordTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PasswordTextField.setForeground(new java.awt.Color(153, 153, 153));
        PasswordTextField.setText("******************");
        PasswordTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordTextFieldFocusLost(evt);
            }
        });
        getContentPane().add(PasswordTextField);
        PasswordTextField.setBounds(290, 280, 379, 30);

        updateBtn.setBackground(new java.awt.Color(72, 118, 168));
        updateBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(this::updateBtnActionPerformed);
        getContentPane().add(updateBtn);
        updateBtn.setBounds(586, 383, 124, 42);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        Account Account = new Account();
        Account.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void newUsernameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newUsernameTextFieldFocusGained
        // TODO add your handling code here:
         if (newUsernameTextField.getText().equals("Enter Your Username")){
            newUsernameTextField.setText("");
        }
    }//GEN-LAST:event_newUsernameTextFieldFocusGained

    private void newUsernameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newUsernameTextFieldFocusLost
        // TODO add your handling code here:
        if (newUsernameTextField.getText().equals("")){
            newUsernameTextField.setText("Enter Your Username");
        }
    }//GEN-LAST:event_newUsernameTextFieldFocusLost

    private void PasswordTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordTextFieldFocusGained
        // TODO add your handling code here:
        if (PasswordTextField.getText().equals("******************")){
            PasswordTextField.setText("");
        }
    }//GEN-LAST:event_PasswordTextFieldFocusGained

    private void PasswordTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordTextFieldFocusLost
        // TODO add your handling code here:
        if (PasswordTextField.getText().equals("")){
            PasswordTextField.setText("******************");
        }
    }//GEN-LAST:event_PasswordTextFieldFocusLost

    private void newUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newUsernameTextFieldActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ChangeUsername_Interface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PasswordTextField;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField newUsernameTextField;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
