/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author oakin
 */
public class ChangePassword_Interface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChangePassword_Interface.class.getName());

    /**
     * Creates new form ChangePassword_Interface
     */
    public ChangePassword_Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        oldPasswordTextField = new javax.swing.JTextField();
        newPasswordTextField = new javax.swing.JTextField();
        confirmPasswordTextField = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(72, 118, 168));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Change Password");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(185, 38, 281, 59);

        backBtn.setBackground(new java.awt.Color(159, 175, 192));
        backBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("←Back");
        backBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        backBtn.addActionListener(this::backBtnActionPerformed);
        jPanel1.add(backBtn);
        backBtn.setBounds(24, 47, 133, 45);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 118);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setText("Old Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(39, 179, 215, 44);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("New Password:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(39, 253, 215, 44);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setText("Confirm Password:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(39, 320, 238, 44);

        oldPasswordTextField.setBackground(new java.awt.Color(204, 204, 204));
        oldPasswordTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        oldPasswordTextField.setText("******************");
        oldPasswordTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                oldPasswordTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                oldPasswordTextFieldFocusLost(evt);
            }
        });
        getContentPane().add(oldPasswordTextField);
        oldPasswordTextField.setBounds(331, 190, 379, 22);

        newPasswordTextField.setBackground(new java.awt.Color(204, 204, 204));
        newPasswordTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newPasswordTextField.setText("******************");
        newPasswordTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newPasswordTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                newPasswordTextFieldFocusLost(evt);
            }
        });
        getContentPane().add(newPasswordTextField);
        newPasswordTextField.setBounds(331, 264, 379, 23);

        confirmPasswordTextField.setBackground(new java.awt.Color(204, 204, 204));
        confirmPasswordTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        confirmPasswordTextField.setText("******************");
        confirmPasswordTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmPasswordTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmPasswordTextFieldFocusLost(evt);
            }
        });
        getContentPane().add(confirmPasswordTextField);
        confirmPasswordTextField.setBounds(331, 331, 379, 23);

        saveBtn.setBackground(new java.awt.Color(72, 118, 168));
        saveBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(this::saveBtnActionPerformed);
        getContentPane().add(saveBtn);
        saveBtn.setBounds(331, 399, 124, 42);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        Account Account = new Account();
        Account.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void oldPasswordTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_oldPasswordTextFieldFocusGained
        // TODO add your handling code here:
         if (oldPasswordTextField.getText().equals("******************")){
            oldPasswordTextField.setText("");
        }
    }//GEN-LAST:event_oldPasswordTextFieldFocusGained

    private void oldPasswordTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_oldPasswordTextFieldFocusLost
        // TODO add your handling code here:
         if (oldPasswordTextField.getText().equals("")){
            oldPasswordTextField.setText("******************");
        }
    }//GEN-LAST:event_oldPasswordTextFieldFocusLost

    private void newPasswordTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newPasswordTextFieldFocusGained
        // TODO add your handling code here:
         if (newPasswordTextField.getText().equals("******************")){
            newPasswordTextField.setText("");
        }
    }//GEN-LAST:event_newPasswordTextFieldFocusGained

    private void newPasswordTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newPasswordTextFieldFocusLost
        // TODO add your handling code here:
        if (newPasswordTextField.getText().equals("")){
            newPasswordTextField.setText("******************");
        }
    }//GEN-LAST:event_newPasswordTextFieldFocusLost

    private void confirmPasswordTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPasswordTextFieldFocusGained
        // TODO add your handling code here:
        if (confirmPasswordTextField.getText().equals("******************")){
            confirmPasswordTextField.setText("");
        }
    }//GEN-LAST:event_confirmPasswordTextFieldFocusGained

    private void confirmPasswordTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPasswordTextFieldFocusLost
        // TODO add your handling code here:
        if (confirmPasswordTextField.getText().equals("")){
            confirmPasswordTextField.setText("******************");
        }
    }//GEN-LAST:event_confirmPasswordTextFieldFocusLost

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ChangePassword_Interface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField confirmPasswordTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField newPasswordTextField;
    private javax.swing.JTextField oldPasswordTextField;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
