/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.PlaySource;
import Model.Song;
import java.util.ArrayList;
import java.util.List;
import service.PlaybackManager;

/**
 * Liked Songs view - displays user's favorited songs
 * Clicking a song sends full playlist to PlaybackManager with LIKED_SONGS
 * source
 *
 * @author rohit
 */
public class likedsong extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(likedsong.class.getName());
    private List<Song> likedSongs = new ArrayList<>();

    /**
     * Creates new form likedsong
     */
    public likedsong() {
        initComponents();
        initializeLikedSongs();
    }

    /**
     * Initialize the list of liked songs (placeholder data)
     * TODO: Load from database in production
     */
    private void initializeLikedSongs() {
        // This is placeholder data - in production, load from database/file
        // For now, create dummy songs for demonstration
        likedSongs.add(new Song("Die With A Smile", "Lady Gaga, Bruno Mars", "Die With A Smile", 213, ""));
        likedSongs.add(new Song("Espresso", "Sabrina Carpenter", "Short n' Sweet", 194, ""));
        likedSongs.add(new Song("Song 3", "Artist 3", "Album 3", 200, ""));
        likedSongs.add(new Song("Song 4", "Artist 4", "Album 4", 210, ""));
        likedSongs.add(new Song("Song 5", "Artist 5", "Album 5", 205, ""));
        likedSongs.add(new Song("Song 6", "Artist 6", "Album 6", 215, ""));
        likedSongs.add(new Song("Song 7", "Artist 7", "Album 7", 200, ""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Backbtn = new javax.swing.JButton();
        NowPlaying = new javax.swing.JPanel();
        nowPlayingSongJLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        LikedSongTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(95, 138, 184));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(95, 138, 184));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel2.setForeground(new java.awt.Color(80, 135, 193));
        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mellow logo.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 200, 129);

        search1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/meteor-icons_search.png"))); // NOI18N
        search1.addActionListener(this::search1ActionPerformed);
        jPanel2.add(search1);
        search1.setBounds(330, 60, 71, 50);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(null);
        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 153, 956, 0);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setText("Search");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(410, 60, 360, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(-4, -10, 1040, 170);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 28)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Liked Songs");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 160, 300, 50);

        Backbtn.setBackground(java.awt.SystemColor.activeCaption);
        Backbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 22)); // NOI18N
        Backbtn.setForeground(new java.awt.Color(255, 255, 255));
        Backbtn.setText("←Back");
        Backbtn.addActionListener(this::BackbtnActionPerformed);
        jPanel1.add(Backbtn);
        Backbtn.setBounds(770, 580, 110, 30);

        NowPlaying.setBackground(new java.awt.Color(95, 138, 184));
        NowPlaying.setForeground(new java.awt.Color(102, 102, 102));
        NowPlaying.setLayout(null);

        nowPlayingSongJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nowPlayingSongJLabel.setText("Song");
        NowPlaying.add(nowPlayingSongJLabel);
        nowPlayingSongJLabel.setBounds(80, 30, 200, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nowplaying.PNG"))); // NOI18N
        NowPlaying.add(jLabel11);
        jLabel11.setBounds(40, 0, 270, 70);

        jPanel1.add(NowPlaying);
        NowPlaying.setBounds(-10, 560, 310, 80);

        LikedSongTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "SN", "Title ", "Artist", "Duration"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(LikedSongTable);
        if (LikedSongTable.getColumnModel().getColumnCount() > 0) {
            LikedSongTable.getColumnModel().getColumn(0).setResizable(false);
            LikedSongTable.getColumnModel().getColumn(1).setResizable(false);
            LikedSongTable.getColumnModel().getColumn(2).setResizable(false);
            LikedSongTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jScrollPane1.setViewportView(jScrollPane2);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(210, 220, 540, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        if (jTextField1.getText().equals("Search")){
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        if (jTextField1.getText().equals("")){
            jTextField1.setText("Search");
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_searchActionPerformed

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_search1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_search1ActionPerformed

    private void song3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_song3ActionPerformed
        // Play liked song 6
        playSongFromLiked(5);
    }// GEN-LAST:event_song3ActionPerformed

    private void song6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_song6ActionPerformed
        // Play liked song 7
        playSongFromLiked(6);
    }// GEN-LAST:event_song6ActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BackbtnActionPerformed
        // Navigate back to the UserDashboard without stopping playback
        UserDashboard dashboard = new UserDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_BackbtnActionPerformed

    private void song1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_song1ActionPerformed
        // Play liked song 1
        playSongFromLiked(0);
    }// GEN-LAST:event_song1ActionPerformed

    private void song2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_song2ActionPerformed
        // Play liked song 2
        playSongFromLiked(1);
    }// GEN-LAST:event_song2ActionPerformed

    private void song4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_song4ActionPerformed
        // Play liked song 3
        playSongFromLiked(2);
    }// GEN-LAST:event_song4ActionPerformed

    private void song5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_song5ActionPerformed
        // Play liked song 4
        playSongFromLiked(3);
    }// GEN-LAST:event_song5ActionPerformed

    private void song7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_song7ActionPerformed
        // Play liked song 5
        playSongFromLiked(4);
    }// GEN-LAST:event_song7ActionPerformed

    /**
     * Helper method to play a liked song at given index
     * Sends full liked songs list and index to PlaybackManager
     */
    private void playSongFromLiked(int index) {
        if (index >= 0 && index < likedSongs.size()) {
            Song selectedSong = likedSongs.get(index);

            // Send full liked songs list and selected index to PlaybackManager
            PlaybackManager.getInstance().setPlaylist(likedSongs, index, PlaySource.LIKED_SONGS);

            // Open Player UI with correct play source
            Player playerWindow = Player.getInstance();
            playerWindow.setPlaySource(PlaySource.LIKED_SONGS);
            playerWindow.setVisible(true);

            logger.info("Playing from Liked Songs: " + selectedSong.getTitle());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new likedsong().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JTable LikedSongTable;
    private javax.swing.JPanel NowPlaying;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel nowPlayingSongJLabel;
    private javax.swing.JButton search1;
    // End of variables declaration//GEN-END:variables
}
