/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author rohit
 */
public class likedsong extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(likedsong.class.getName());

    /**
     * Creates new form likedsong
     */
    public likedsong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        search1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        song1 = new javax.swing.JButton();
        song2 = new javax.swing.JButton();
        song3 = new javax.swing.JButton();
        song4 = new javax.swing.JButton();
        song5 = new javax.swing.JButton();
        song6 = new javax.swing.JButton();
        song7 = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(994, 725));
        setPreferredSize(new java.awt.Dimension(994, 725));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(95, 138, 184));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(95, 138, 184));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel2.setForeground(new java.awt.Color(80, 135, 193));
        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mellow logo.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 200, 129);

        search.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        search.setForeground(java.awt.SystemColor.controlShadow);
        search.setText("Search");
        search.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        search.addActionListener(this::searchActionPerformed);
        jPanel2.add(search);
        search.setBounds(409, 76, 445, 38);

        search1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/meteor-icons_search.png"))); // NOI18N
        search1.addActionListener(this::search1ActionPerformed);
        jPanel2.add(search1);
        search1.setBounds(332, 76, 71, 38);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(null);
        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 153, 956, 0);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(-4, -10, 1040, 170);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 28)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Liked Songs");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 180, 300, 50);

        song1.setBackground(new java.awt.Color(95, 138, 184));
        song1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        song1.setForeground(new java.awt.Color(255, 255, 255));
        song1.setText("\"Die With A Smile\" - Lady Gaga, Bruno Mars");
        song1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(song1);
        song1.setBounds(50, 270, 470, 31);

        song2.setBackground(new java.awt.Color(95, 138, 184));
        song2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        song2.setForeground(new java.awt.Color(255, 255, 255));
        song2.setText("\"Espresso\" - Sabrina Carpenter");
        song2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(song2);
        song2.setBounds(50, 310, 470, 31);

        song3.setBackground(new java.awt.Color(95, 138, 184));
        song3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        song3.setForeground(new java.awt.Color(255, 255, 255));
        song3.setText("\"Good Luck, Babe!\" - Chappell Roan");
        song3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        song3.addActionListener(this::song3ActionPerformed);
        jPanel1.add(song3);
        song3.setBounds(50, 350, 470, 31);

        song4.setBackground(new java.awt.Color(95, 138, 184));
        song4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        song4.setForeground(new java.awt.Color(255, 255, 255));
        song4.setText("\"As It Was\" - Harry Styles");
        song4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(song4);
        song4.setBounds(50, 390, 470, 31);

        song5.setBackground(new java.awt.Color(95, 138, 184));
        song5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        song5.setForeground(new java.awt.Color(255, 255, 255));
        song5.setText(".......");
        song5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(song5);
        song5.setBounds(50, 430, 470, 31);

        song6.setBackground(new java.awt.Color(95, 138, 184));
        song6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        song6.setForeground(new java.awt.Color(255, 255, 255));
        song6.setText(".......");
        song6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        song6.addActionListener(this::song6ActionPerformed);
        jPanel1.add(song6);
        song6.setBounds(50, 470, 470, 31);

        song7.setBackground(new java.awt.Color(95, 138, 184));
        song7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        song7.setForeground(new java.awt.Color(255, 255, 255));
        song7.setText("........");
        song7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(song7);
        song7.setBounds(50, 510, 470, 31);

        backbtn.setBackground(java.awt.SystemColor.activeCaption);
        backbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 22)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("←Back");
        backbtn.addActionListener(this::backbtnActionPerformed);
        jPanel1.add(backbtn);
        backbtn.setBounds(780, 570, 110, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("1.");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 270, 41, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("2.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 310, 20, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("3.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 350, 20, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("4.");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 390, 20, 25);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("5.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 430, 18, 25);

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("6.");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 470, 18, 25);

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("7.");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 510, 18, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search1ActionPerformed

    private void song3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_song3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_song3ActionPerformed

    private void song6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_song6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_song6ActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        UserDashboard UserDashboard = new UserDashboard();
        UserDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new likedsong().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton search;
    private javax.swing.JButton search1;
    private javax.swing.JButton song1;
    private javax.swing.JButton song2;
    private javax.swing.JButton song3;
    private javax.swing.JButton song4;
    private javax.swing.JButton song5;
    private javax.swing.JButton song6;
    private javax.swing.JButton song7;
    // End of variables declaration//GEN-END:variables
}
