/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import Model.PlaylistModel;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.*;

/**
 * PlaylistCard - Reusable component for displaying playlist cards
 * Supports two modes: NORMAL (opens PlaylistFile) and CRUD (opens
 * Playlist_Edit)
 * 
 * @author oakin
 */
public class PlaylistCard extends javax.swing.JPanel {

    /**
     * Mode enum for card behavior
     */
    public enum Mode {
        NORMAL, // Click opens PlaylistFile.java
        CRUD, // Click opens Playlist_Edit.java with confirmation
        ADD // Click adds song to playlist
    }

    private final PlaylistModel playlist;
    private final Mode mode;
    private JLabel songCountLabel;

    /**
     * Creates new form PlaylistCard with data and mode
     * 
     * @param playlist      The playlist data to display
     * @param mode          The interaction mode (NORMAL or CRUD)
     * @param clickListener Click event handler
     */
    public PlaylistCard(PlaylistModel playlist, Mode mode, Runnable clickListener) {
        this.playlist = playlist;
        this.mode = mode;
        initComponents();
        setupCard(clickListener);
    }

    /**
     * Default constructor for form builder (not recommended for actual use)
     */
    public PlaylistCard() {
        this.playlist = null;
        this.mode = Mode.NORMAL;
        initComponents();
    }

    /**
     * Setup card with data and click behavior
     */
    private void setupCard(Runnable clickListener) {
        if (playlist == null)
            return;

        // Set playlist name
        playlistNameJLabel.setText(playlist.getPlaylistName());
        playlistNameJLabel.setFont(new Font("Segoe UI", Font.BOLD, 16));
        playlistNameJLabel.setForeground(new Color(51, 51, 51));

        // Add song count label
        songCountLabel = new JLabel(playlist.getSongCount() + " songs");
        songCountLabel.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        songCountLabel.setForeground(new Color(102, 102, 102));
        songCountLabel.setHorizontalAlignment(SwingConstants.CENTER);

        // Update layout to include song count
        removeAll();
        setLayout(new BorderLayout(5, 5));
        setBackground(new Color(230, 230, 230));
        setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(180, 180, 180), 1),
                BorderFactory.createEmptyBorder(15, 10, 15, 10)));
        setPreferredSize(new Dimension(180, 120));
        setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Create center panel for labels
        JPanel centerPanel = new JPanel();
        centerPanel.setLayout(new BoxLayout(centerPanel, BoxLayout.Y_AXIS));
        centerPanel.setOpaque(false);

        playlistNameJLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        songCountLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        centerPanel.add(Box.createVerticalGlue());
        centerPanel.add(playlistNameJLabel);
        centerPanel.add(Box.createRigidArea(new Dimension(0, 5)));
        centerPanel.add(songCountLabel);
        centerPanel.add(Box.createVerticalGlue());

        add(centerPanel, BorderLayout.CENTER);

        // Add hover effect
        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                setBackground(new Color(200, 220, 240));
                setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createLineBorder(new Color(89, 141, 193), 2),
                        BorderFactory.createEmptyBorder(14, 9, 14, 9)));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                setBackground(new Color(230, 230, 230));
                setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createLineBorder(new Color(180, 180, 180), 1),
                        BorderFactory.createEmptyBorder(15, 10, 15, 10)));
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                if (clickListener != null) {
                    clickListener.run();
                }
            }
        });
    }

    /**
     * Get the playlist associated with this card
     */
    public PlaylistModel getPlaylist() {
        return playlist;
    }

    /**
     * Get the mode of this card
     */
    public Mode getMode() {
        return mode;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playlistNameJLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        playlistNameJLabel.setText("Playlist Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(28, Short.MAX_VALUE)
                                .addComponent(playlistNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(playlistNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(57, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel playlistNameJLabel;
    // End of variables declaration//GEN-END:variables
}
