/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Dao.PlaylistDao;
import Model.PlaySource;
import Model.Song;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import service.PlaybackManager;

/**
 * PlaylistFile view - displays songs in a specific playlist
 * Clicking a song plays it with PLAYLIST source
 */
public class PlaylistFile extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(PlaylistFile.class.getName());

    private final int playlistId;
    private final String playlistName;
    private final PlaylistDao playlistDao;
    private List<Song> playlistSongs;

    /**
     * Creates new form PlaylistFile with playlist ID
     */
    public PlaylistFile(int playlistId, String playlistName) {
        this.playlistId = playlistId;
        this.playlistName = playlistName;
        this.playlistDao = new PlaylistDao();

        initComponents();
        loadPlaylistSongs();

        // After initComponents, configure NowPlaying panel with NowPlayingCard
        NowPlaying.removeAll();
        NowPlaying.setLayout(new BorderLayout());
        NowPlaying.setOpaque(true);
        NowPlaying.setBackground(new java.awt.Color(97, 139, 181));
        NowPlaying.add(new NowPlayingCard(), BorderLayout.CENTER);
        NowPlaying.setPreferredSize(new java.awt.Dimension(0, 80));
        NowPlaying.revalidate();
        NowPlaying.repaint();
    }

    /**
     * Default constructor for form builder (not recommended for actual use)
     */
    public PlaylistFile() {
        this.playlistId = -1;
        this.playlistName = "Unknown Playlist";
        this.playlistDao = new PlaylistDao();
        initComponents();

        // After initComponents, configure NowPlaying panel with NowPlayingCard
        NowPlaying.removeAll();
        NowPlaying.setLayout(new BorderLayout());
        NowPlaying.setOpaque(true);
        NowPlaying.setBackground(new java.awt.Color(97, 139, 181));
        NowPlaying.add(new NowPlayingCard(), BorderLayout.CENTER);
        NowPlaying.setPreferredSize(new java.awt.Dimension(0, 80));
        NowPlaying.revalidate();
        NowPlaying.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        playlistNameJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        PlaylistTable = new javax.swing.JTable();
        BackToPlaylist = new javax.swing.JButton();
        NowPlaying = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(97, 139, 181));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mellow logo.png"))); // NOI18N

        playlistNameJLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        playlistNameJLabel.setText("Your Songs");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(playlistNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 604, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playlistNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        PlaylistTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "SN", "Title", "Artist", "Duration"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(PlaylistTable);
        if (PlaylistTable.getColumnModel().getColumnCount() > 0) {
            PlaylistTable.getColumnModel().getColumn(0).setResizable(false);
            PlaylistTable.getColumnModel().getColumn(1).setResizable(false);
            PlaylistTable.getColumnModel().getColumn(2).setResizable(false);
            PlaylistTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jScrollPane1.setViewportView(jScrollPane2);

        BackToPlaylist.setBackground(new java.awt.Color(149, 184, 220));
        BackToPlaylist.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BackToPlaylist.setText("←Back");
        BackToPlaylist.setBorder(null);
        BackToPlaylist.addActionListener(this::BackToPlaylistActionPerformed);

        NowPlaying.setBackground(new java.awt.Color(97, 139, 181));
        NowPlaying.setLayout(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NowPlaying, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackToPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(BackToPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(NowPlaying, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackToPlaylistActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BackToPlaylistActionPerformed
        // TODO add your handling code here:
        Playlist Playlist = new Playlist();
        Playlist.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_BackToPlaylistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PlaylistFile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToPlaylist;
    private javax.swing.JPanel NowPlaying;
    private javax.swing.JTable PlaylistTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel playlistNameJLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * Load songs from the playlist and render in table
     */
    private void loadPlaylistSongs() {
        if (playlistId <= 0) {
            logger.warning("Invalid playlist ID: " + playlistId);
            return;
        }

        // Set playlist name
        playlistNameJLabel.setText(playlistName);

        // Fetch songs from database
        playlistSongs = playlistDao.getPlaylistSongs(playlistId);

        if (playlistSongs == null || playlistSongs.isEmpty()) {
            logger.info("No songs in playlist: " + playlistName);
            return;
        }

        // Render songs in table
        renderSongsTable();

        logger.info("Loaded " + playlistSongs.size() + " songs from playlist: " + playlistName);
    }

    /**
     * Render songs in the PlaylistTable
     * Columns: Song Name, Artist, Duration
     */
    private void renderSongsTable() {
        DefaultTableModel model = new DefaultTableModel(
                new String[] { "Song Name", "Artist", "Duration" }, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Make table read-only
            }
        };

        for (Song song : playlistSongs) {
            String duration = formatDuration(song.getDurationSeconds());
            model.addRow(new Object[] {
                    song.getTitle(),
                    song.getArtist(),
                    duration
            });
        }

        PlaylistTable.setModel(model);
        PlaylistTable.setFillsViewportHeight(true);

        // Set column widths
        if (PlaylistTable.getColumnModel().getColumnCount() > 0) {
            PlaylistTable.getColumnModel().getColumn(0).setPreferredWidth(250); // Song Name
            PlaylistTable.getColumnModel().getColumn(1).setPreferredWidth(200); // Artist
            PlaylistTable.getColumnModel().getColumn(2).setPreferredWidth(100); // Duration
        }

        // Add click listener to play song
        PlaylistTable.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = PlaylistTable.rowAtPoint(evt.getPoint());
                if (row >= 0 && row < playlistSongs.size()) {
                    Song selectedSong = playlistSongs.get(row);

                    // Send full playlist and selected index to PlaybackManager
                    PlaybackManager.getInstance().setPlaylist(playlistSongs, row, PlaySource.PLAYLIST);

                    // Open Player UI with correct play source
                    Player playerWindow = Player.getInstance();
                    playerWindow.setPlaySource(PlaySource.PLAYLIST);
                    playerWindow.setVisible(true);

                    logger.info("Playing from Playlist '" + playlistName + "': " + selectedSong.getTitle());
                }
            }
        });
    }

    /**
     * Format duration from seconds to MM:SS
     */
    private String formatDuration(int seconds) {
        int minutes = seconds / 60;
        int secs = seconds % 60;
        return String.format("%d:%02d", minutes, secs);
    }
}
