/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.SongController;
import Dao.PlaylistDao;
import Model.PlaySource;
import Model.PlaylistModel;
import Model.Song;
import Model.UserSession;
import java.awt.*;
import java.util.List;
import javax.swing.*;
import service.PlaybackManager;

/**
 * Playlist view - displays user's playlists as cards
 * Each card shows playlist name and song count
 * Clicking a card opens PlaylistFile.java
 */
public class Playlist extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Playlist.class.getName());

    private final SongController songController;
    private final PlaylistDao playlistDao;
    private JList<Song> songList;
    private List<Song> playlistSongs; // For future extension: filtering songs into playlists

    /**
     * Creates new form Playlist with a shared controller.
     */
    public Playlist(SongController controller) {
        this.songController = controller;
        this.playlistDao = new PlaylistDao();
        initComponents();
        initSongList();
        loadPlaylistCards();

        // After initComponents, configure NowPlaying panel with NowPlayingCard
        NowPlaying.removeAll();
        NowPlaying.setLayout(new BorderLayout());
        NowPlaying.setOpaque(true);
        NowPlaying.setBackground(new java.awt.Color(89, 141, 193));
        NowPlaying.add(new NowPlayingCard(), BorderLayout.CENTER);
        NowPlaying.setPreferredSize(new java.awt.Dimension(0, 80));
        NowPlaying.revalidate();
        NowPlaying.repaint();
    }

    // Default constructor for builder/runtime compatibility (not used by dashboard)
    public Playlist() {
        this.songController = new SongController();
        this.playlistDao = new PlaylistDao();
        initComponents();
        initSongList();
        loadPlaylistCards();

        // After initComponents, configure NowPlaying panel with NowPlayingCard
        NowPlaying.removeAll();
        NowPlaying.setLayout(new BorderLayout());
        NowPlaying.setOpaque(true);
        NowPlaying.setBackground(new java.awt.Color(89, 141, 193));
        NowPlaying.add(new NowPlayingCard(), BorderLayout.CENTER);
        NowPlaying.setPreferredSize(new java.awt.Dimension(0, 80));
        NowPlaying.revalidate();
        NowPlaying.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BackBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        SearchTextField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        Createnew = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NowPlaying = new javax.swing.JPanel();
        playlistCardRendererPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(89, 141, 193));
        jPanel1.setLayout(null);

        BackBtn.setBackground(new java.awt.Color(153, 153, 153));
        BackBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(255, 255, 255));
        BackBtn.setText("←Back");
        BackBtn.setBorder(null);
        BackBtn.addActionListener(this::BackBtnActionPerformed);
        jPanel1.add(BackBtn);
        BackBtn.setBounds(840, 590, 110, 40);

        jPanel2.setBackground(new java.awt.Color(89, 141, 193));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        SearchTextField.setBackground(new java.awt.Color(153, 153, 153));
        SearchTextField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SearchTextField.setText("Search");
        SearchTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchTextFieldFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchTextFieldFocusLost(evt);
            }
        });
        SearchTextField.addActionListener(this::SearchTextFieldActionPerformed);

        searchBtn.setBackground(new java.awt.Color(153, 153, 153));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/meteor-icons_search.png"))); // NOI18N

        Createnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/createNewPlaylistBtn_image.jpg"))); // NOI18N
        Createnew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Createnew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Createnew.setIconTextGap(0);
        Createnew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Createnew.addActionListener(this::CreatenewActionPerformed);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mellow logo.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Create New Playlist");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                .createSequentialGroup()
                                                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(57, 57, 57)
                                                .addComponent(Createnew, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(153, 153, 153))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(123, 123, 123)))));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Createnew, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(-10, 0, 1080, 170);

        NowPlaying.setBackground(new java.awt.Color(89, 141, 193));
        NowPlaying.setForeground(new java.awt.Color(102, 102, 102));
        NowPlaying.setLayout(null);
        jPanel1.add(NowPlaying);
        NowPlaying.setBounds(20, 570, 520, 80);

        playlistCardRendererPanel.setBackground(new java.awt.Color(89, 141, 193));

        javax.swing.GroupLayout playlistCardRendererPanelLayout = new javax.swing.GroupLayout(
                playlistCardRendererPanel);
        playlistCardRendererPanel.setLayout(playlistCardRendererPanelLayout);
        playlistCardRendererPanelLayout.setHorizontalGroup(
                playlistCardRendererPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 970, Short.MAX_VALUE));
        playlistCardRendererPanelLayout.setVerticalGroup(
                playlistCardRendererPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 320, Short.MAX_VALUE));

        jPanel1.add(playlistCardRendererPanel);
        playlistCardRendererPanel.setBounds(10, 250, 970, 320);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Playlist");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 180, 200, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1025,
                                javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchTextFieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_SearchTextFieldFocusLost
        // TODO add your handling code here:
        if (SearchTextField.getText().equals("")) {
            SearchTextField.setText("Search");
        }
    }// GEN-LAST:event_SearchTextFieldFocusLost

    private void SearchTextFieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_SearchTextFieldFocusGained
        // TODO add your handling code here:
        if (SearchTextField.getText().equals("Search")) {
            SearchTextField.setText("");
        }
    }// GEN-LAST:event_SearchTextFieldFocusGained

    private void CreatenewActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CreatenewActionPerformed
        // Prompt user for playlist name
        String playlistName = JOptionPane.showInputDialog(this, "Enter playlist name:", "Create New Playlist",
                JOptionPane.PLAIN_MESSAGE);

        if (playlistName != null && !playlistName.trim().isEmpty()) {
            UserSession session = UserSession.getInstance();
            if (session.isLoggedIn()) {
                int userId = session.getUserId();
                int newPlaylistId = playlistDao.createPlaylist(userId, playlistName.trim());

                if (newPlaylistId > 0) {
                    logger.info("Created playlist: " + playlistName + " (ID: " + newPlaylistId + ")");
                    JOptionPane.showMessageDialog(this, "Playlist created successfully!", "Success",
                            JOptionPane.INFORMATION_MESSAGE);

                    // Reload playlist cards
                    loadPlaylistCards();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to create playlist", "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "You must be logged in to create playlists", "Error",
                        JOptionPane.WARNING_MESSAGE);
            }
        }
    }// GEN-LAST:event_CreatenewActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        UserDashboard UserDashboard = new UserDashboard();
        UserDashboard.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_BackBtnActionPerformed

    private void SearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SearchTextFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_SearchTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Playlist().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton Createnew;
    private javax.swing.JPanel NowPlaying;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel playlistCardRendererPanel;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables

    /**
     * Load and render playlist cards for logged-in user
     * Each card shows playlist name and song count
     * Clicking a card opens PlaylistFile.java
     */
    private void loadPlaylistCards() {
        UserSession session = UserSession.getInstance();
        if (!session.isLoggedIn()) {
            logger.warning("User not logged in - cannot load playlists");
            return;
        }

        int userId = session.getUserId();
        List<PlaylistModel> playlists = playlistDao.getUserPlaylists(userId);

        // Clear existing cards
        playlistCardRendererPanel.removeAll();

        // Use GridLayout for dynamic card rendering
        int columns = 3; // 3 cards per row
        int rows = (int) Math.ceil(playlists.size() / (double) columns);
        playlistCardRendererPanel.setLayout(new GridLayout(rows, columns, 20, 20));

        // Create a card for each playlist
        for (PlaylistModel playlist : playlists) {
            JPanel card = createPlaylistCard(playlist);
            playlistCardRendererPanel.add(card);
        }

        playlistCardRendererPanel.revalidate();
        playlistCardRendererPanel.repaint();

        logger.info("Loaded " + playlists.size() + " playlists for user " + userId);
    }

    /**
     * Create a visual card for a playlist
     * Shows playlist name and song count
     * Clicking opens PlaylistFile.java
     */
    private JPanel createPlaylistCard(PlaylistModel playlist) {
        JPanel card = new JPanel();
        card.setLayout(new BorderLayout());
        card.setBackground(new Color(164, 183, 203));
        card.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
        card.setPreferredSize(new Dimension(200, 150));
        card.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Playlist name
        JLabel nameLabel = new JLabel(playlist.getPlaylistName(), SwingConstants.CENTER);
        nameLabel.setFont(new Font("Segoe UI", Font.BOLD, 16));
        nameLabel.setForeground(Color.BLACK);

        // Song count
        JLabel countLabel = new JLabel(playlist.getSongCount() + " songs", SwingConstants.CENTER);
        countLabel.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        countLabel.setForeground(new Color(60, 60, 60));

        // Layout
        JPanel textPanel = new JPanel();
        textPanel.setLayout(new BoxLayout(textPanel, BoxLayout.Y_AXIS));
        textPanel.setOpaque(false);
        textPanel.add(Box.createVerticalGlue());
        textPanel.add(nameLabel);
        textPanel.add(Box.createRigidArea(new Dimension(0, 10)));
        textPanel.add(countLabel);
        textPanel.add(Box.createVerticalGlue());

        card.add(textPanel, BorderLayout.CENTER);

        // Click listener - open PlaylistFile with this playlist
        card.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openPlaylistFile(playlist.getPlaylistId(), playlist.getPlaylistName());
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                card.setBackground(new Color(140, 163, 183)); // Darker on hover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                card.setBackground(new Color(164, 183, 203)); // Original color
            }
        });

        return card;
    }

    /**
     * Open PlaylistFile.java with the selected playlist
     */
    private void openPlaylistFile(int playlistId, String playlistName) {
        PlaylistFile playlistFile = new PlaylistFile(playlistId, playlistName);
        playlistFile.setVisible(true);
        this.dispose();
        logger.info("Opening playlist: " + playlistName + " (ID: " + playlistId + ")");
    }

    /**
     * Initialize song list by loading songs from SongCache via SongController.
     * Does not scan local files - uses pre-loaded songs from cache.
     * Supports future extension for filtering songs into specific playlists.
     */
    private void initSongList() {
        // Load songs from SongCache via SongController (no file scanning)
        playlistSongs = songController.getAllSongs();

        songList = new JList<>(new DefaultListModel<>());
        DefaultListModel<Song> model = (DefaultListModel<Song>) songList.getModel();

        // Populate the list with all songs (future: filter by playlist)
        if (playlistSongs != null) {
            for (Song s : playlistSongs) {
                model.addElement(s);
            }
        }

        songList.setCellRenderer(new ListCellRenderer<>());
        songList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        // Double-click to play song from playlist
        // Send full playlist and selected index to PlaybackManager
        songList.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2) {
                    Song selectedSong = songList.getSelectedValue();
                    if (selectedSong != null && playlistSongs != null) {
                        int selectedIndex = playlistSongs.indexOf(selectedSong);

                        // Send full playlist and selected index to PlaybackManager
                        PlaybackManager.getInstance().setPlaylist(playlistSongs, selectedIndex, PlaySource.PLAYLIST);

                        // Open Player UI with correct play source
                        Player playerWindow = Player.getInstance();
                        playerWindow.setPlaySource(PlaySource.PLAYLIST);
                        playerWindow.setVisible(true);

                        logger.info("Playing from Playlist: " + selectedSong.getTitle());
                    }
                }
            }
        });

        JScrollPane scroll = new JScrollPane(songList);
        scroll.setBounds(40, 340, 830, 180);
        jPanel1.add(scroll);
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    private static class ListCellRenderer<T extends Song> extends DefaultListCellRenderer {
        @Override
        public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected,
                boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (value instanceof Song s) {
                String duration = formatDuration(s.getDurationSeconds());
                setText(s.getTitle() + "  —  " + s.getArtist() + "  (" + duration + ")");
            }
            return this;
        }

        private String formatDuration(int seconds) {
            int m = seconds / 60;
            int s = seconds % 60;
            return String.format("%d:%02d", m, s);
        }
    }
}
