/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Dao.PlaylistDao;
import Dao.PlaylistSongDao;
import Model.PlaylistModel;
import Model.Song;
import java.awt.*;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import service.PlaylistManager;

/**
 * Playlist_Edit - Edit playlist name and manage songs
 * Allows updating playlist name and removing songs from playlist
 */
public class Playlist_Edit extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(Playlist_Edit.class.getName());

    private final PlaylistModel playlist;
    private final PlaylistDao playlistDao;
    private final PlaylistSongDao playlistSongDao;
    private List<Song> playlistSongs;

    /**
     * Creates new form Playlist_Edit with playlist data
     */
    public Playlist_Edit(PlaylistModel playlist) {
        this.playlist = playlist;
        this.playlistDao = new PlaylistDao();
        this.playlistSongDao = new PlaylistSongDao();

        initComponents();
        setupUI();
        loadPlaylistSongs();

        // Configure NowPlaying panel
        NowPlaying.removeAll();
        NowPlaying.setLayout(new BorderLayout());
        NowPlaying.setOpaque(true);
        NowPlaying.setBackground(new java.awt.Color(89, 141, 193));
        NowPlaying.add(new NowPlayingCard(), BorderLayout.CENTER);
        NowPlaying.setPreferredSize(new java.awt.Dimension(0, 80));
        NowPlaying.revalidate();
        NowPlaying.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BackBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        SearchTextField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NowPlaying = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        PlaylistTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        playlistNameTextField = new javax.swing.JTextField();
        deleteSongBtn = new javax.swing.JButton();
        saveChangesBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(89, 141, 193));
        jPanel1.setLayout(null);

        BackBtn.setBackground(new java.awt.Color(153, 153, 153));
        BackBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(255, 255, 255));
        BackBtn.setText("←Back");
        BackBtn.setBorder(null);
        BackBtn.addActionListener(this::BackBtnActionPerformed);
        jPanel1.add(BackBtn);
        BackBtn.setBounds(840, 590, 110, 40);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        SearchTextField.setBackground(new java.awt.Color(153, 153, 153));
        SearchTextField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SearchTextField.setText("Search");
        SearchTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchTextFieldFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchTextFieldFocusLost(evt);
            }
        });
        SearchTextField.addActionListener(this::SearchTextFieldActionPerformed);

        searchBtn.setBackground(new java.awt.Color(153, 153, 153));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/meteor-icons_search.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mellow logo.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("Edit Playlist Songs");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(330, 330, 330))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(178, 178, 178)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 321,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)))));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(-10, 0, 1080, 130);

        NowPlaying.setBackground(new java.awt.Color(89, 141, 193));
        NowPlaying.setForeground(new java.awt.Color(102, 102, 102));
        NowPlaying.setLayout(null);
        jPanel1.add(NowPlaying);
        NowPlaying.setBounds(10, 640, 520, 80);

        PlaylistTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "SN", "Title", "Artist", "Duration"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane2.setViewportView(PlaylistTable);

        jScrollPane1.setViewportView(jScrollPane2);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(190, 230, 600, 300);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 150, 70, 40);

        playlistNameTextField.setText("name");
        playlistNameTextField.addActionListener(this::playlistNameTextFieldActionPerformed);
        jPanel1.add(playlistNameTextField);
        playlistNameTextField.setBounds(120, 160, 210, 30);

        deleteSongBtn.setBackground(new java.awt.Color(255, 51, 51));
        deleteSongBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deleteSongBtn.setText("Delete");
        deleteSongBtn.addActionListener(this::deleteSongBtnActionPerformed);
        jPanel1.add(deleteSongBtn);
        deleteSongBtn.setBounds(830, 240, 110, 40);

        saveChangesBtn.setBackground(new java.awt.Color(0, 153, 204));
        saveChangesBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        saveChangesBtn.setText("Save");
        jPanel1.add(saveChangesBtn);
        saveChangesBtn.setBounds(830, 300, 110, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1025,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 12, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playlistNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_playlistNameTextFieldActionPerformed
        // No action needed on enter
    }// GEN-LAST:event_playlistNameTextFieldActionPerformed

    private void deleteSongBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteSongBtnActionPerformed
        deleteSong();
    }// GEN-LAST:event_deleteSongBtnActionPerformed

    private void SearchTextFieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_SearchTextFieldFocusLost
        // TODO add your handling code here:
        if (SearchTextField.getText().equals("")) {
            SearchTextField.setText("Search");
        }
    }// GEN-LAST:event_SearchTextFieldFocusLost

    private void SearchTextFieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_SearchTextFieldFocusGained
        // TODO add your handling code here:
        if (SearchTextField.getText().equals("Search")) {
            SearchTextField.setText("");
        }
    }// GEN-LAST:event_SearchTextFieldFocusGained

    /**
     * Setup UI components with playlist data
     */
    private void setupUI() {
        // Set playlist name in text field
        playlistNameTextField.setText(playlist.getPlaylistName());

        // Add save button action listener
        saveChangesBtn.addActionListener(e -> saveChanges());

        setTitle("Edit Playlist - " + playlist.getPlaylistName());
    }

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BackBtnActionPerformed
        goBack();
    }// GEN-LAST:event_BackBtnActionPerformed

    private void SearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SearchTextFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_SearchTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        // Note: Playlist_Edit requires a PlaylistModel parameter
        // It should be opened from Playlist_CRUD.java, not run directly
        System.out.println("Playlist_Edit cannot be run directly. Open from Playlist_CRUD.");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JPanel NowPlaying;
    private javax.swing.JTable PlaylistTable;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JButton deleteSongBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField playlistNameTextField;
    private javax.swing.JButton saveChangesBtn;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables

    /**
     * Load songs from playlist using PlaylistSongDao
     */
    private void loadPlaylistSongs() {
        playlistSongs = playlistSongDao.getSongsByPlaylistId(playlist.getPlaylistId());

        DefaultTableModel model = new DefaultTableModel(
                new String[] { "ID", "Title", "Artist", "Album", "Duration" }, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (Song song : playlistSongs) {
            model.addRow(new Object[] {
                    song.getSongId(),
                    song.getTitle(),
                    song.getArtist(),
                    song.getAlbum(),
                    formatDuration(song.getDurationSeconds())
            });
        }

        PlaylistTable.setModel(model);
        PlaylistTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        PlaylistTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        PlaylistTable.getColumnModel().getColumn(2).setPreferredWidth(150);
        PlaylistTable.getColumnModel().getColumn(3).setPreferredWidth(150);
        PlaylistTable.getColumnModel().getColumn(4).setPreferredWidth(80);

        logger.info("Loaded " + playlistSongs.size() + " songs for playlist: " + playlist.getPlaylistName());
    }

    /**
     * Delete selected song from playlist
     */
    private void deleteSong() {
        int selectedRow = PlaylistTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this,
                    "Please select a song to delete",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int songId = (int) PlaylistTable.getValueAt(selectedRow, 0);
        String songTitle = (String) PlaylistTable.getValueAt(selectedRow, 1);

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to remove \"" + songTitle + "\" from this playlist?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            boolean success = playlistSongDao.removeSongFromPlaylist(playlist.getPlaylistId(), songId);
            if (success) {
                JOptionPane.showMessageDialog(this,
                        "Song removed successfully",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                loadPlaylistSongs(); // Refresh table
            } else {
                JOptionPane.showMessageDialog(this,
                        "Failed to remove song",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * Save playlist name changes
     */
    private void saveChanges() {
        String newName = playlistNameTextField.getText().trim();

        if (newName.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Playlist name cannot be empty",
                    "Invalid Name",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean success = playlistDao.updatePlaylistName(playlist.getPlaylistId(), newName);

        if (success) {
            JOptionPane.showMessageDialog(this,
                    "Playlist updated successfully",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);

            // Refresh PlaylistManager cache
            PlaylistManager.getInstance().refreshCache();

            // Go back to Playlist view
            goBack();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Failed to update playlist",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Go back to Playlist view
     */
    private void goBack() {
        Playlist playlistView = new Playlist();
        playlistView.setVisible(true);
        this.dispose();
    }

    /**
     * Format duration from seconds to MM:SS
     */
    private String formatDuration(int seconds) {
        int minutes = seconds / 60;
        int secs = seconds % 60;
        return String.format("%d:%02d", minutes, secs);
    }

    /**
     * Old method - not used anymore (kept for form compatibility)
     */
    private void loadPlaylistCards() {
        // Not used in this implementation
    }

    /**
     * Old method - not used anymore (kept for form compatibility)
     */
    private JPanel createPlaylistCard(PlaylistModel p) {
        // Not used in this implementation
        return new JPanel();
    }

    /**
     * Old method - not used anymore (kept for form compatibility)
     */
    private void openPlaylistFile(int playlistId, String playlistName) {
        // Not used in this implementation
    }

    /**
     * Old method - not used anymore (kept for form compatibility)
     */
    private void initSongList() {
        // Not used in this implementation
    }
}