/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.SongController;
import Model.PlaySource;
import Model.Song;
import java.awt.Image;
import java.io.File;
import java.nio.file.Path;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import service.PlaybackManager;
import utils.NowPlayingState;

/**
 *
 * @author Asus
 */
public class UserDashboard extends javax.swing.JFrame implements utils.NowPlayingState.NowPlayingListener {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(UserDashboard.class.getName());
    private final SongController songController = new SongController();
    private List<Song> loadedSongs;
    private static boolean songsLoadedOnce = false;

    /**
     * Creates new form UserDashboard
     */
    public UserDashboard() {
        initComponents();
        setRecentlyPlayedColumnWidths();
        jTable1.setFillsViewportHeight(true);

        // Display logged-in username
        Model.UserSession session = Model.UserSession.getInstance();
        if (session.isLoggedIn()) {
            Userdisplay.setText("Hello, " + session.getUsername());
        }

        // STEP 1: Load local songs once during application startup
        if (!songsLoadedOnce) {
            logger.info("Starting to load local songs from Music directory...");

            // Use dynamic, safe path - NOT hardcoded
            String musicPath = System.getProperty("user.home") + File.separator + "Music";
            songController.loadLocalSongsOnce(musicPath);
            songsLoadedOnce = true;

            logger.info("Local songs loading completed.");
        }

        // STEP 2: Fetch all songs AFTER loading
        List<Song> allSongs = songController.getAllSongs();
        logger.info("Total songs fetched from cache: " + (allSongs != null ? allSongs.size() : 0));

        // STEP 3: Render songs if available
        if (allSongs != null && !allSongs.isEmpty()) {
            logger.info("Starting dashboard rendering with " + allSongs.size() + " songs...");

            // Store in loadedSongs for UI interaction
            loadedSongs = allSongs;

            // Render recommendation buttons
            loadSongsToUI(allSongs);

            // Render Recently Played table
            renderRecentlyPlayed(allSongs);

            logger.info("Dashboard rendering completed.");
        } else {
            logger.warning("No songs found in cache. Music directory may be empty or inaccessible.");
        }

        // Register as listener for now playing changes
        NowPlayingState.getInstance().addListener(this);

        // Add mouse click listener to recently played table
        // When user clicks a song: load full playlist into PlaybackManager and start
        // playback
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = jTable1.rowAtPoint(evt.getPoint());
                if (row >= 0 && loadedSongs != null && row < loadedSongs.size()) {
                    Song selectedSong = loadedSongs.get(row);

                    // Send full playlist and selected index to PlaybackManager
                    PlaybackManager.getInstance().setPlaylist(loadedSongs, row, PlaySource.DASHBOARD);

                    // Open Player UI with correct play source
                    Player playerWindow = Player.getInstance();
                    playerWindow.setPlaySource(PlaySource.DASHBOARD);
                    playerWindow.setVisible(true);

                    logger.info("Playing from Dashboard: " + selectedSong.getTitle());
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        SearchBar = new javax.swing.JTextField();
        Playlist = new javax.swing.JButton();
        Likedsongs = new javax.swing.JButton();
        Account = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        Reccomendation = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Recs1 = new javax.swing.JButton();
        Recs3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Userdisplay = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Recs2 = new javax.swing.JButton();
        NowPlaying = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        Recs4 = new javax.swing.JButton();
        Likedsongs1 = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mellowlogo.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 10, 210, 140);

        jPanel2.setBackground(new java.awt.Color(228, 181, 172));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Phosphenes.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel9.setText("ARTIST");

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Segoe UI Variable", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Meet Phosphenes, the indie band based in Nepal.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 278, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 171,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(310, 80, 660, 110);

        searchBtn.setBackground(new java.awt.Color(197, 191, 191));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/meteor-icons_search.png"))); // NOI18N
        searchBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(51, 51, 51)));
        jPanel1.add(searchBtn);
        searchBtn.setBounds(310, 30, 70, 30);

        SearchBar.setBackground(new java.awt.Color(160, 148, 148));
        SearchBar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        SearchBar.setForeground(new java.awt.Color(204, 204, 204));
        SearchBar.setText("               Search");
        SearchBar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153),
                new java.awt.Color(102, 102, 102)));
        SearchBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchBarFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchBarFocusLost(evt);
            }
        });
        SearchBar.addActionListener(this::SearchBarActionPerformed);
        jPanel1.add(SearchBar);
        SearchBar.setBounds(310, 30, 650, 30);

        Playlist.setBackground(new java.awt.Color(40, 52, 46));
        Playlist.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Playlist.setForeground(new java.awt.Color(204, 204, 204));
        Playlist.setText("Playlists");
        Playlist.setBorder(null);
        Playlist.addActionListener(this::PlaylistActionPerformed);
        jPanel1.add(Playlist);
        Playlist.setBounds(110, 220, 130, 29);

        Likedsongs.setBackground(new java.awt.Color(40, 52, 46));
        Likedsongs.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Likedsongs.setForeground(new java.awt.Color(204, 204, 204));
        Likedsongs.setText("Liked Songs");
        Likedsongs.setBorder(null);
        Likedsongs.addActionListener(this::LikedsongsActionPerformed);
        jPanel1.add(Likedsongs);
        Likedsongs.setBounds(110, 280, 130, 30);

        Account.setBackground(new java.awt.Color(40, 52, 46));
        Account.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Account.setForeground(new java.awt.Color(204, 204, 204));
        Account.setText("Account");
        Account.setBorder(null);
        Account.addActionListener(this::AccountActionPerformed);
        jPanel1.add(Account);
        Account.setBounds(100, 590, 120, 30);

        logout.setBackground(new java.awt.Color(40, 52, 46));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        logout.setForeground(new java.awt.Color(204, 204, 204));
        logout.setText("Logout");
        logout.setBorder(null);
        logout.addActionListener(this::logoutActionPerformed);
        jPanel1.add(logout);
        logout.setBounds(100, 660, 120, 30);

        Reccomendation.setFont(new java.awt.Font("Segoe UI Variable", 1, 16)); // NOI18N
        Reccomendation.setText("Reccomendation");
        jPanel1.add(Reccomendation);
        Reccomendation.setBounds(310, 200, 150, 20);

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 16)); // NOI18N
        jLabel1.setText("Recently Played");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(310, 440, 120, 30);

        Recs1.setBackground(new java.awt.Color(217, 213, 213));
        Recs1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Recs1.setForeground(new java.awt.Color(153, 153, 153));
        Recs1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sza.jpg"))); // NOI18N
        Recs1.setText("SZA- Snooze");
        Recs1.setBorder(null);
        Recs1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Recs1.setIconTextGap(0);
        Recs1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Recs1.addActionListener(this::Recs1ActionPerformed);
        jPanel1.add(Recs1);
        Recs1.setBounds(280, 230, 210, 200);

        Recs3.setBackground(new java.awt.Color(217, 213, 213));
        Recs3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Recs3.setForeground(new java.awt.Color(153, 153, 153));
        Recs3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Heavy - The Marías.jpg"))); // NOI18N
        Recs3.setText("The Marias- Heavy");
        Recs3.setBorder(null);
        Recs3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Recs3.setIconTextGap(0);
        Recs3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Recs3.addActionListener(this::Recs3ActionPerformed);
        jPanel1.add(Recs3);
        Recs3.setBounds(520, 220, 220, 210);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconamoon_playlist.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 210, 41, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-park-outline_like.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 270, 50, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mdi_account.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 580, 52, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mdi_logout.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 650, 40, 50);

        Userdisplay.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Userdisplay.setForeground(new java.awt.Color(204, 204, 204));
        Userdisplay.setText("Hello,");
        jPanel1.add(Userdisplay);
        Userdisplay.setBounds(30, 150, 230, 20);

        jButton1.setBackground(new java.awt.Color(40, 52, 46));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("All Songs");
        jButton1.setBorder(null);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);
        jButton1.setBounds(110, 350, 130, 30);

        Recs2.setBackground(new java.awt.Color(217, 213, 213));
        Recs2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Recs2.setForeground(new java.awt.Color(153, 153, 153));
        Recs2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wave.jpg"))); // NOI18N
        Recs2.setText("Wave to earth- Ride");
        Recs2.setBorder(null);
        Recs2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Recs2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Recs2.addActionListener(this::Recs2ActionPerformed);
        jPanel1.add(Recs2);
        Recs2.setBounds(750, 230, 210, 210);

        NowPlaying.setBackground(new java.awt.Color(214, 214, 214));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nowplaying.PNG"))); // NOI18N

        javax.swing.GroupLayout NowPlayingLayout = new javax.swing.GroupLayout(NowPlaying);
        NowPlaying.setLayout(NowPlayingLayout);
        NowPlayingLayout.setHorizontalGroup(
                NowPlayingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 280, Short.MAX_VALUE));
        NowPlayingLayout.setVerticalGroup(
                NowPlayingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(NowPlayingLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 66,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 4, Short.MAX_VALUE)));

        jPanel1.add(NowPlaying);
        NowPlaying.setBounds(480, 640, 280, 70);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/allsongs.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 340, 40, 50);

        jTable1.setBackground(new java.awt.Color(225, 223, 223));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "SN", "Title", "Artist", "Duration"
                }) {
            Class[] types = new Class[] {
                    java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        jScrollPane1.setViewportView(jScrollPane2);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(330, 480, 590, 130);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Untitled design (2).png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 990, 730);

        Recs4.setBackground(new java.awt.Color(229, 226, 226));
        Recs4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Recs4.setForeground(new java.awt.Color(153, 153, 153));
        Recs4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Heavy - The Marías.jpg"))); // NOI18N
        Recs4.setText("The Marias- Heavy");
        Recs4.setBorder(null);
        Recs4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Recs4.setIconTextGap(0);
        Recs4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Recs4.addActionListener(this::Recs4ActionPerformed);
        // Don't add Recs4 to panel - it overlaps with Recs3
        // jPanel1.add(Recs4);
        // Recs4.setBounds(560, 350, 150, 150);

        // Likedsongs1 removed - duplicate of Likedsongs button

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SearchBarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_SearchBarActionPerformed

    private void Recs3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Recs3ActionPerformed
        // Recs3 is index 1 (from loadSongsToUI mapping)
        playRecommendationSong(1);
    }// GEN-LAST:event_Recs3ActionPerformed

    private void PlaylistActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PlaylistActionPerformed
        Playlist playlistWindow = new Playlist(songController);
        playlistWindow.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_PlaylistActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logoutActionPerformed
        // Logout and return to Login window
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to logout?",
                "Confirm Logout",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // Clear user session
            Model.UserSession.getInstance().clearSession();

            this.dispose();
            view.Login loginView = new view.Login();
            Controller.LoginController loginController = new Controller.LoginController(loginView);
            loginController.open();
        }
    }// GEN-LAST:event_logoutActionPerformed

    private void AccountActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AccountActionPerformed
        // Only allow Account page when logged in; otherwise redirect to Login
        Model.UserSession session = Model.UserSession.getInstance();
        if (session.isLoggedIn()) {
            Account account = new Account(session.getUsername(), session.getEmail());
            account.setVisible(true);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please login to view your account.",
                    "Login Required",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            view.Login loginView = new view.Login();
            Controller.LoginController loginController = new Controller.LoginController(loginView);
            loginController.open();
        }
    }// GEN-LAST:event_AccountActionPerformed

    private void Recs1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Recs1ActionPerformed
        // Recs1 is index 0 (from loadSongsToUI mapping)
        playRecommendationSong(0);
    }// GEN-LAST:event_Recs1ActionPerformed

    private void Recs4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Recs4ActionPerformed
        // Recs4 is index 2 (from loadSongsToUI mapping)
        playRecommendationSong(2);
    }// GEN-LAST:event_Recs4ActionPerformed

    private void SearchBarFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_SearchBarFocusGained
        // TODO add your handling code here:
        if (SearchBar.getText().equals("               Search")) {
            SearchBar.setText("");
        }
    }// GEN-LAST:event_SearchBarFocusGained

    private void SearchBarFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_SearchBarFocusLost
        // TODO add your handling code here:
        if (SearchBar.getText().equals("")) {
            SearchBar.setText("               Search");
        }
    }// GEN-LAST:event_SearchBarFocusLost

    private void LikedsongsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LikedsongsActionPerformed
        // TODO add your handling code here:
        likedsong likedsong = new likedsong();
        likedsong.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_LikedsongsActionPerformed

    private void Recs2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Recs2ActionPerformed
        // Recs2 is index 3 (from loadSongsToUI mapping)
        playRecommendationSong(3);
    }// GEN-LAST:event_Recs2ActionPerformed

    private void Likedsongs1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Likedsongs1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_Likedsongs1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AllSongs AllSongs = new AllSongs();
        AllSongs.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Account;
    private javax.swing.JButton Likedsongs;
    private javax.swing.JButton Likedsongs1;
    private javax.swing.JPanel NowPlaying;
    private javax.swing.JButton Playlist;
    private javax.swing.JLabel Reccomendation;
    private javax.swing.JButton Recs1;
    private javax.swing.JButton Recs2;
    private javax.swing.JButton Recs3;
    private javax.swing.JButton Recs4;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JLabel Userdisplay;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton logout;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables

    private void loadSongsToUI(List<Song> songs) {
        JButton[] recButtons = { Recs1, Recs3, Recs4, Recs2 };
        loadedSongs = songs;
        for (int i = 0; i < recButtons.length && i < songs.size(); i++) {
            Song song = songs.get(i);
            String duration = String.format("%d:%02d", song.getDurationSeconds() / 60, song.getDurationSeconds() % 60);
            recButtons[i].setText(song.getTitle() + " - " + song.getArtist() + " (" + duration + ")");

            // Load image
            ImageIcon icon;
            try {
                icon = new ImageIcon(getClass().getResource(song.getImagePath()));
            } catch (Exception e) {
                icon = new ImageIcon(getClass().getResource("/Images/default_song.jpg"));
            }
            Image img = icon.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
            recButtons[i].setIcon(new ImageIcon(img));

            recButtons[i].setHorizontalTextPosition(SwingConstants.CENTER);
            recButtons[i].setVerticalTextPosition(SwingConstants.BOTTOM);
        }
    }

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int res = chooser.showOpenDialog(this);
        if (res == JFileChooser.APPROVE_OPTION) {
            File selected = chooser.getSelectedFile();
            Path root = selected.toPath();
            songController.loadSongs(root);
            loadSongsToUI(songController.getSongs());
        }
    }

    private void setRecentlyPlayedColumnWidths() {
        javax.swing.table.TableColumnModel columns = jTable1.getColumnModel();
        columns.getColumn(0).setMinWidth(35);
        columns.getColumn(0).setPreferredWidth(45);
        columns.getColumn(0).setMaxWidth(55);
        columns.getColumn(1).setPreferredWidth(240);
        columns.getColumn(2).setPreferredWidth(180);
        columns.getColumn(3).setMinWidth(60);
        columns.getColumn(3).setPreferredWidth(70);
        columns.getColumn(3).setMaxWidth(80);
    }

    /**
     * Play a recommendation song by index
     * Sends playlist and selected index to PlaybackManager and opens Player
     */
    private void playRecommendationSong(int index) {
        if (loadedSongs == null || index < 0 || index >= loadedSongs.size()) {
            logger.warning("Invalid recommendation song index: " + index);
            return;
        }

        Song selectedSong = loadedSongs.get(index);

        // Send full playlist and selected index to PlaybackManager
        PlaybackManager.getInstance().setPlaylist(loadedSongs, index, PlaySource.DASHBOARD);

        // Open Player UI with correct play source
        Player playerWindow = Player.getInstance();
        playerWindow.setPlaySource(PlaySource.DASHBOARD);
        playerWindow.setVisible(true);

        logger.info("Playing from Dashboard recommendation: " + selectedSong.getTitle());
    }

    /**
     * Render recently played songs in the JTable.
     * Displays up to the first 10 songs with Title, Artist, and Duration.
     * Follows MVC principles - View only renders data from Controller.
     * 
     * @param songs List of songs to display
     */
    private void renderRecentlyPlayed(List<Song> songs) {
        logger.info("renderRecentlyPlayed called with " + (songs != null ? songs.size() : 0) + " songs");

        // Get the table model
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        // Verify table structure
        int columnCount = model.getColumnCount();
        logger.info("JTable column count: " + columnCount);

        // Clear existing rows
        model.setRowCount(0);

        if (songs == null || songs.isEmpty()) {
            logger.warning("No songs to render in Recently Played table.");
            return;
        }

        // Display up to the first 10 songs
        int limit = Math.min(10, songs.size());
        logger.info("Rendering " + limit + " songs in Recently Played table...");

        for (int i = 0; i < limit; i++) {
            Song song = songs.get(i);
            String title = song.getTitle();
            String artist = song.getArtist();
            int durationSeconds = song.getDurationSeconds();
            String duration = String.format("%d:%02d", durationSeconds / 60, durationSeconds % 60);

            model.addRow(new Object[] { i + 1, title, artist, duration });
        }

        logger.info("Successfully added " + model.getRowCount() + " rows to Recently Played table.");
    }

    /**
     * Listen for now playing changes to update UI
     */
    @Override
    public void onNowPlayingChanged(Song song, boolean playing) {
        if (song == null) {
            logger.fine("Playback stopped");
            return;
        }

        logger.info("Now playing: " + song.getTitle() + " - " + song.getArtist());
        // UI updates can be added here if needed (e.g., highlight currently playing
        // song)
    }
}
