/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Asus
 */
public class UserDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserDashboard.class.getName());

    /**
     * Creates new form UserDashboard
     */
    public UserDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        SearchBar = new javax.swing.JTextField();
        Playlist = new javax.swing.JButton();
        Likedsongs = new javax.swing.JButton();
        Account = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        Reccomendation = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Recs1 = new javax.swing.JButton();
        Recs3 = new javax.swing.JButton();
        Recent1 = new javax.swing.JButton();
        Recent2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Userdisplay = new javax.swing.JLabel();
        Recent3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Recs4 = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mellowlogo.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 10, 210, 140);

        jPanel2.setBackground(new java.awt.Color(228, 181, 172));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Phosphenes.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel9.setText("ARTIST");

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Segoe UI Variable", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Meet Phosphenes, the indie band based in Nepal.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(310, 140, 650, 130);

        searchBtn.setBackground(new java.awt.Color(197, 191, 191));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/meteor-icons_search.png"))); // NOI18N
        searchBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(51, 51, 51)));
        jPanel1.add(searchBtn);
        searchBtn.setBounds(310, 50, 70, 30);

        SearchBar.setBackground(new java.awt.Color(160, 148, 148));
        SearchBar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        SearchBar.setForeground(new java.awt.Color(204, 204, 204));
        SearchBar.setText("               Search");
        SearchBar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        SearchBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchBarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchBarFocusLost(evt);
            }
        });
        SearchBar.addActionListener(this::SearchBarActionPerformed);
        jPanel1.add(SearchBar);
        SearchBar.setBounds(310, 50, 650, 30);

        Playlist.setBackground(new java.awt.Color(40, 52, 46));
        Playlist.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Playlist.setForeground(new java.awt.Color(204, 204, 204));
        Playlist.setText("Playlists");
        Playlist.setBorder(null);
        Playlist.addActionListener(this::PlaylistActionPerformed);
        jPanel1.add(Playlist);
        Playlist.setBounds(110, 220, 130, 29);

        Likedsongs.setBackground(new java.awt.Color(40, 52, 46));
        Likedsongs.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Likedsongs.setForeground(new java.awt.Color(204, 204, 204));
        Likedsongs.setText("Liked Songs");
        Likedsongs.setBorder(null);
        jPanel1.add(Likedsongs);
        Likedsongs.setBounds(110, 280, 130, 30);

        Account.setBackground(new java.awt.Color(40, 52, 46));
        Account.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Account.setForeground(new java.awt.Color(204, 204, 204));
        Account.setText("Account");
        Account.setBorder(null);
        Account.addActionListener(this::AccountActionPerformed);
        jPanel1.add(Account);
        Account.setBounds(100, 590, 120, 30);

        logout.setBackground(new java.awt.Color(40, 52, 46));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        logout.setForeground(new java.awt.Color(204, 204, 204));
        logout.setText("Logout");
        logout.setBorder(null);
        logout.addActionListener(this::logoutActionPerformed);
        jPanel1.add(logout);
        logout.setBounds(100, 660, 120, 30);

        Reccomendation.setFont(new java.awt.Font("Segoe UI Variable", 1, 16)); // NOI18N
        Reccomendation.setText("Reccomendation");
        jPanel1.add(Reccomendation);
        Reccomendation.setBounds(310, 310, 150, 20);

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 16)); // NOI18N
        jLabel1.setText("Recently Played");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(310, 520, 120, 30);

        Recs1.setBackground(new java.awt.Color(217, 213, 213));
        Recs1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Recs1.setForeground(new java.awt.Color(153, 153, 153));
        Recs1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sza.jpg"))); // NOI18N
        Recs1.setText("SZA- Snooze");
        Recs1.setBorder(null);
        Recs1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Recs1.setIconTextGap(0);
        Recs1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Recs1.addActionListener(this::Recs1ActionPerformed);
        jPanel1.add(Recs1);
        Recs1.setBounds(320, 350, 150, 150);

        Recs3.setBackground(new java.awt.Color(217, 213, 213));
        Recs3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Recs3.setForeground(new java.awt.Color(153, 153, 153));
        Recs3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Heavy - The Marías.jpg"))); // NOI18N
        Recs3.setText("The Marias- Heavy");
        Recs3.setBorder(null);
        Recs3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Recs3.setIconTextGap(0);
        Recs3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Recs3.addActionListener(this::Recs3ActionPerformed);
        jPanel1.add(Recs3);
        Recs3.setBounds(560, 350, 150, 150);

        Recent1.setBackground(new java.awt.Color(196, 195, 195));
        Recent1.setForeground(new java.awt.Color(102, 102, 102));
        Recent1.setText("Song 1");
        Recent1.addActionListener(this::Recent1ActionPerformed);
        jPanel1.add(Recent1);
        Recent1.setBounds(310, 580, 410, 20);

        Recent2.setBackground(new java.awt.Color(196, 195, 195));
        Recent2.setForeground(new java.awt.Color(102, 102, 102));
        Recent2.setText("Song 2");
        Recent2.addActionListener(this::Recent2ActionPerformed);
        jPanel1.add(Recent2);
        Recent2.setBounds(310, 620, 410, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconamoon_playlist.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 210, 41, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-park-outline_like.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 270, 50, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mdi_account.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 580, 52, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mdi_logout.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 650, 40, 50);

        Userdisplay.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Userdisplay.setForeground(new java.awt.Color(204, 204, 204));
        Userdisplay.setText("Hello,");
        jPanel1.add(Userdisplay);
        Userdisplay.setBounds(140, 150, 120, 20);

        Recent3.setBackground(new java.awt.Color(196, 195, 195));
        Recent3.setForeground(new java.awt.Color(102, 102, 102));
        Recent3.setText("Song 3");
        jPanel1.add(Recent3);
        Recent3.setBounds(310, 660, 410, 20);

        jButton2.setBackground(new java.awt.Color(217, 213, 213));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 153, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wave.jpg"))); // NOI18N
        jButton2.setText("Wave to earth- Ride");
        jButton2.setBorder(null);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jButton2);
        jButton2.setBounds(790, 350, 150, 150);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Untitled design (2).png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1010, 740);

        Recs4.setBackground(new java.awt.Color(229, 226, 226));
        Recs4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Recs4.setForeground(new java.awt.Color(153, 153, 153));
        Recs4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Heavy - The Marías.jpg"))); // NOI18N
        Recs4.setText("The Marias- Heavy");
        Recs4.setBorder(null);
        Recs4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Recs4.setIconTextGap(0);
        Recs4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Recs4.addActionListener(this::Recs4ActionPerformed);
        jPanel1.add(Recs4);
        Recs4.setBounds(560, 350, 150, 150);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBarActionPerformed

    private void Recent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Recent2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Recent2ActionPerformed

    private void Recs3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Recs3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Recs3ActionPerformed

    private void PlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaylistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlaylistActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int choice = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to logout?",
        "confirm logout",
        javax.swing.JOptionPane.YES_NO_OPTION
        );
        if (choice==javax.swing.JOptionPane.YES_OPTION){
            Login Login = new Login();
            Login.setVisible(true);
            this.dispose();
        }
        else{
            UserDashboard UserDashboard = new UserDashboard();
            UserDashboard.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountActionPerformed
        // TODO add your handling code here:
        Account Account = new Account();
        Account.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AccountActionPerformed

    private void Recent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Recent1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Recent1ActionPerformed

    private void Recs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Recs1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Recs1ActionPerformed

    private void Recs4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Recs4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Recs4ActionPerformed

    private void SearchBarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchBarFocusGained
        // TODO add your handling code here:
        if(SearchBar.getText().equals("               Search")){
            SearchBar.setText("");  
        }
    }//GEN-LAST:event_SearchBarFocusGained

    private void SearchBarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchBarFocusLost
        // TODO add your handling code here:
        if(SearchBar.getText().equals("")){
            SearchBar.setText("               Search");
        }
    }//GEN-LAST:event_SearchBarFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Account;
    private javax.swing.JButton Likedsongs;
    private javax.swing.JButton Playlist;
    private javax.swing.JLabel Reccomendation;
    private javax.swing.JButton Recent1;
    private javax.swing.JButton Recent2;
    private javax.swing.JButton Recent3;
    private javax.swing.JButton Recs1;
    private javax.swing.JButton Recs3;
    private javax.swing.JButton Recs4;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JLabel Userdisplay;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton logout;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables
}
